export const LOGIN_INFO = 'LOGIN_INFO';
export const APP_VERSION = 'APP_VERSION';

export const USER_DATA = 'USER_DATA'
export const LOGIN_STATUS = 'LOGIN_STATUS'
export const EMPTY_LOADER = 'EMPTY_LOADER'
export const LOCATION_DATA ='LOCATION_DATA'
export const SELECTED_BRANCH ='SELECTED_BRANCH'
export const SELECTED_HOME_APP_ITEM ='SELECTED_HOME_APP_ITEM'
export const SELECTED_HOME_WORK_ITEM ='SELECTED_HOME_WORK_ITEM'
export const SELECTED_HOME_DELIVERY_ITEM ='SELECTED_HOME_DELIVERY_ITEM'
export const SELECTED_HOME_READY_DELIVERY_ITEM ='SELECTED_HOME_READY_DELIVERY_ITEM'
export const JOBCARD_DATASHEET_REFRESH = 'JOBCARD_DATASHEET_REFRESH'
export const HOME_SELECT_DATA  = 'HOME_SELECT_DATA'
export const PREJOBCARD_REFRESH = 'PREJOBCARD_REFRESH'
export const HOME_REFRESH = 'HOME_REFRESH'
export const BOOKING_DETAIL = 'BOOKING_DETAIL'
export const VEHICLE_DETAIL_FROM_CHASSIS_NUMBER = 'VEHICLE_DETAIL_FROM_CHASSIS_NUMBER'





 