import React from 'react'
import { StyleSheet } from 'react-native'
import * as constant from '../../utilities/constants'
const styles = StyleSheet.create({
    mainTopView:{
    backgroundColor:constant.whiteGhost,
    flex:1,
    margin:constant.moderateScale(5),
    borderRadius:10,
    elevation:1,
    },
    tabMainView:{
    paddingBottom:'1%',
    height:constant.moderateScale(50)
    },
    tabSubView:{
     flex:1,
     borderBottomWidth:0.8,
     borderBottomColor:'red',
     flexDirection:'row',
     justifyContent:'space-between',
     marginHorizontal:'3%',
     paddingTop:constant.moderateScale(5),
    },
    tabButton:{
    flex:1,
    justifyContent:'center'
    },
    tabButtonText:{
        fontSize:constant.moderateScale(15),
        color:constant.red,
        fontFamily:constant.typeMedium,
    marginTop:constant.moderateScale(4),

    },
    tabButton2:{
        flex:1,
        justifyContent:'center'  
    },
    tabButtonText2:{
    fontSize:constant.moderateScale(15),
    color:constant.textColor,
    fontFamily:constant.typeLight,
    marginTop:constant.moderateScale(4),

    },
    horixontalLine:{
        height:constant.moderateScale(4),
        width:constant.moderateScale(35),
        backgroundColor:'red',
        position:'absolute',
        bottom:-constant.moderateScale(2),
        borderRadius:constant.resW(20)
    },
    detailMainView:{
    paddingHorizontal:"3%",
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-between',
    marginTop:constant.moderateScale(5)
    },
    detailText:{
        fontSize:constant.moderateScale(14),
        color:'#424242',
        width:constant.moderateScale(115),
        fontFamily:constant.typeLight
    },
    text2:{
        fontSize:constant.moderateScale(14),
        color:constant.red,  
    },
    dropList:{
      borderWidth:1,
      height:constant.moderateScale(40),
      flex:1,
      borderRadius:10,
      borderColor:'#ABABAB',
      backgroundColor:constant.whiteColor,
    },
    dropListText:{
        fontSize:constant.moderateScale(15),
        color:constant.textColor,
        fontFamily:constant.typeLight,
    },
    mobileSubView:{
    flex:1,
    flexDirection:'row',
    alignItems:'center'
    },
    input1:{
        borderWidth:1,
        height:constant.moderateScale(40),
        flex:1,
        borderRadius:10,
        borderColor:'#ABABAB',
        backgroundColor:constant.whiteColor,
        color:constant.blackColor,
        fontFamily:constant.typeLight,
        paddingHorizontal:"3%",
        fontSize:constant.moderateScale(15)
    },
    searchButtonStyle:{
    alignItems:'center',
    justifyContent:'center',
    },
    searchStyle:{
        height:constant.moderateScale(50),
        width:constant.moderateScale(50),
    },
    detailMainView2:{
        paddingHorizontal:"2%",
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginTop:"2%"
        },
    bottomMainView:{
    backgroundColor:constant.whiteColor,
    marginHorizontal:'1%',
    borderRadius:10,
    elevation:1,
    marginTop:'3%',
    paddingBottom:'2%'
    },
    calenderStyle:{
        height:constant.moderateScale(25),
        width:constant.moderateScale(25),
        marginRight:'2%'
    },
    calenderMainView:{
    flex:1,
    flexDirection:'row',
    alignItems:'center',
    borderWidth:1,
    borderRadius:10,
    borderColor:'#ABABAB',
    paddingLeft:"3%",

    },
    calenderInput:{
        height:constant.moderateScale(40),
        flex:1,
        borderRadius:10,
        borderColor:'#ABABAB',
        backgroundColor:constant.whiteColor,
        color:constant.blackColor,
        fontFamily:constant.typeLight,
        fontSize:constant.moderateScale(14)
    },
    proceedButton:{
     width:constant.moderateScale(135),
     alignSelf:'center',
     marginTop:constant.resW(30),
     marginBottom:constant.resW(5)
    },
    proccedButtonText:{

    },
    dropNameList:{
        borderWidth:1,
        height:constant.moderateScale(40),
        borderRadius:8,
        width:constant.resW(17),
        borderColor:'#ABABAB',
        backgroundColor:constant.whiteColor,
       paddingHorizontal:0
      },
      dropNameList2:{
        borderWidth:1,
        height:constant.moderateScale(40),
        borderRadius:8,
        width:constant.resW(17),
        borderColor:'#ABABAB',
        backgroundColor:constant.whiteColor,
       paddingHorizontal:constant.moderateScale(5)
      },
      dropNameListText:{
          fontSize:constant.moderateScale(14),
          color:constant.textColor,
          fontFamily:constant.typeLight,
      },
      refInput:{
        height:constant.moderateScale(40),
        flex:1,
        backgroundColor:constant.whiteColor,
        color:'#4AAA38',
        fontFamily:constant.typeMedium,
        fontSize:constant.moderateScale(15)
      },
      coutMainView:{
       flex:1,
       flexDirection:'row',
       alignItems:'center',
       justifyContent:'center'
      },
      coutButton:{
    //   backgroundColor:constant.red,
      height:constant.moderateScale(40),
      width:constant.moderateScale(40),
      borderRadius:7,
      alignItems:'center',
      justifyContent:'center'
      },
      counttext:{
        fontFamily:constant.typeMedium,
        fontSize:constant.font34,
        color:constant.red,
        
      },
      countInput:{
        height:constant.moderateScale(35),
         borderWidth:1,
        borderRadius:8,
        backgroundColor:constant.whiteColor,
        width:constant.moderateScale(100),
      alignItems:'center',
      justifyContent:'center' ,
      marginHorizontal:constant.moderateScale(10)   ,
      borderColor:constant.red  
      },
      countInputText:{
        color:constant.blackColor,
        fontFamily:constant.typeLight,
        fontSize:constant.moderateScale(15),
      },
      commentInput:{
        borderWidth:1,
        height:constant.moderateScale(90),
        flex:1,
        borderRadius:10,
        borderColor:'#ABABAB',
        backgroundColor:constant.whiteColor,
        color:constant.blackColor,
        fontFamily:constant.typeLight,
        paddingHorizontal:"3%",
        fontSize:constant.moderateScale(14),
        textAlignVertical:'top'
    },
    minusStyle:{
        height:constant.moderateScale(20),
        width:constant.moderateScale(20),
    }
})

export default styles;